FROM openjdk:8-jdk-alpine
ARG JAR_FILE
# RUN echo ${JAR_FILE}
COPY target/vehicle-monitor-1.0.0-SNAPSHOT.jar app.jar
EXPOSE 8081
CMD ["java", "-jar", "app.jar", "--eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka"]
# CMD ["java", "-jar", "app.jar"]